spring.application.name=sctec-empreendedorismo-backend-api

# Nome do profile ativo ao usar esse arquivo
spring.profiles.active=dev

# Nivel de logging de mensagens no output console
logging.level.root=info

# 8080 eh a porta default do spring boot, declarada aqui apenas para ficar explicito
server.port=8080

# Para retornar as mensagens personalizadas do tratamento de exceptions
spring.web.error.include-message=always

#
# Configuracao H2 database
#
spring.datasource.url=jdbc:h2:mem:sctecdb
# Demais configs
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite acesso a console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
# Criar o banco de dados na inicializacao da aplicacao
spring.jpa.defer-datasource-initialization=true

#
# Hibernate logging
#
# Nivel de logging, DEBUG mostra todas as queries
logging.level.org.hibernate.SQL=DEBUG
# Formatar as queries para deixar mais legivel no looging
spring.jpa.properties.hibernate.format_sql=true
# Mostrar parametros nas queries, TRACE para mostrar
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#
# Spring Docs
#
# URI da documentacao em formato json
springdoc.api-docs.path=/api-docs
# URI da documentacao em formato pagina html
springdoc.swagger-ui.path=/api-docs.html
# Ordem que os endpoints aparecem na pagina html
springdoc.swagger-ui.operationsSorter=alpha
