spring.application.name=sctec-empreendedorismo-backend-api

# nome do porfile ativo ao usar esse arquivo
spring.profiles.active=dev

# nivel de logging de mensagens no output console
logging.level.root=info

# 8080 eh a porta default do spring boot, declarada aqui apenas para ficar explicito
server.port=8080

#
# Configuracao H2 database
#
spring.datasource.url=jdbc:h2:mem:sctecdb
# Demais configs
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite acesso a console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
# Criar o banco de dados na inicializacao da aplicacao
spring.jpa.defer-datasource-initialization=true

#
# Hibernate logging
#
# Nivel de logging, DEBUG mostra todas as queries
logging.level.org.hibernate.SQL=DEBUG
# Formatar as queries para deixar mais legivel no looging
spring.jpa.properties.hibernate.format_sql=true
# Mostrar parametros nas queries, TRACE para mostrar
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
