spring.application.name=sctec-empreendedorismo-backend-api

# 8080 eh a porta default, declarada aqui apenas para ver
server.port=8080

#
# Configuracao H2 database
#
# Persistir em arquivo, para nao perder os dados ao restartar a aplicacao
spring.datasource.url=jdbc:h2:file:/data/demo
# Demais configs
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite acesso a console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
